# Generated by Django 3.2.25 on 2024-12-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampDetails',
            fields=[
                ('camp_id', models.AutoField(primary_key=True, serialize=False)),
                ('camp_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('no_of_refugees', models.IntegerField(db_column='no.of_refugees')),
                ('no_of_volunteers', models.IntegerField(db_column='no.of_volunteers')),
            ],
            options={
                'db_table': 'camp_details',
                'managed': False,
            },
        ),
    ]
