# Generated by Django 3.2.25 on 2024-12-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminReg',
            fields=[
                ('admin_id', models.AutoField(db_column='Admin_id', primary_key=True, serialize=False)),
                ('admin_name', models.CharField(db_column='Admin_name', max_length=45)),
                ('designation', models.CharField(max_length=45)),
                ('user_name', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('contact_no', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'admin_reg',
                'managed': False,
            },
        ),
    ]
