# Generated by Django 3.2.25 on 2024-12-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerActivites',
            fields=[
                ('activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('activity', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'volunteer_activites',
                'managed': False,
            },
        ),
    ]
