# Generated by Django 3.2.25 on 2024-12-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('requirement_id', models.AutoField(primary_key=True, serialize=False)),
                ('requirements', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
            ],
            options={
                'db_table': 'requirements',
                'managed': False,
            },
        ),
    ]
